cd server
bash build_image.sh
cd ..
cd controller
bash build_image.sh
cd ..
cd components/thermometer
bash build_image.sh
cd ../..
cd envSimulator
bash build_image.sh
cd ..
cd components/alarm
bash build_image.sh
cd ../..
cd components/light_sensor
bash build_image.sh
cd ../..
cd components/move_sensor
bash build_image.sh
cd ../..
cd components/blinds
bash build_image.sh
cd ../..
cd components/lights
bash build_image.sh
cd ../..
cd components/radiator
bash build_image.sh
cd ../..
