version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_VHOST: "smarthome"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - smart
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    labels:
      NAME: "rabbitmq"
  log:
    environment:
        RABBIT_HOST: "rabbitmq"
    image: "smarthome/server"
    hostname: "log-server"
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    networks:
      - smart
  thermometer:
    environment:
        RABBIT_HOST: "rabbitmq"
    image: "smarthome/thermometer"
    hostname: "thermometer"
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    networks:
      - smart
  controller:
    environment:
      RABBIT_HOST: "rabbitmq"
    image: "smarthome/controller"
    hostname: "controller"
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - smart
  alarm:
    environment:
      RABBIT_HOST: "rabbitmq"
    image: "smarthome/alarm"
    hostname: "alarm"
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - smart
  env_simulator:
    environment:
      RABBIT_HOST: "rabbitmq"
    image: "smarthome/env_simulator"
    hostname: "env_simulator"
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - smart
  light_sensor:
    environment:
      RABBIT_HOST: "rabbitmq"
    image: "smarthome/server"
    hostname: "light-sensor"
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - smart
  move_sensor:
    environment:
      RABBIT_HOST: "rabbitmq"
    image: "smarthome/server"
    hostname: "move-sensor"
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - smart
  blinds:
    environment:
      RABBIT_HOST: "rabbitmq"
    image: "smarthome/blinds"
    hostname: "blinds"
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - smart
  lights:
    environment:
      RABBIT_HOST: "rabbitmq"
    image: "smarthome/lights"
    hostname: "lights"
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - smart
  radiator:
    environment:
      RABBIT_HOST: "rabbitmq"
    image: "smarthome/radiator"
    hostname: "radiator"
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - smart
networks:
  smart:
    driver: bridge

